### PR TITLE
Fixes styles for icons on external links

### PR DESCRIPTION
**Pull request by imaustink**
image

### CODE REVIEW

**Review by chasenlehara — APPROVED** [review]
Hm, I wonder why it was being done in a more complicated way before…

**Comment by imaustink** [comment]
Would you like me to merge this? I have access, just not sure if you want me to do that.

**Comment by chasenlehara** [comment]
@imaustink Always feel free to merge your own PRs. 😊

You’ll also want to make a new release of this package once all your changes have been merged.

**Comment by imaustink** [comment]
Alright sounds good, thanks!

**Pull request merged**
