### PR TITLE
Upgrade for bit docs

### PR DESCRIPTION
**Pull request by leoj3n**
Begins work related to https://github.com/donejs/bit-docs-donejs-theme/issues/71

### CODE REVIEW

**Comment by leoj3n** [comment]
Commit `Fix path to steal.production.js` helps with https://github.com/donejs/donejs/issues/1032

**Comment by leoj3n** [comment]
@justinbmeyer Perhaps you can assign one of your guys to this task? Personally I don't have the historical knowledge or understanding needed to complete the upgrade from CanJS 2.3 to CanJS 5 for this very outdated theme (`bit-docs-donejs-theme`).

**Comment by justinbmeyer** [comment]
There's no one available to do this currently.

Here's the relevant upgrade guides:

- https://canjs.com/doc/migrate-3.html
- https://canjs.com/doc/migrate-4.html
- https://canjs.com/doc/migrate-5.html (likely not needed b/c this theme doesn't use any model stuff and that's what changed from 4 to 5).

**Comment by cherifGsoul** [comment]
I just saw this now, I made similar fixes in this PR https://github.com/donejs/bit-docs-donejs-theme/pull/79.

**Comment by cherifGsoul** [comment]
Fixed in #79

**Pull request closed without merging**
